### ISSUE TITLE
goto code - line 25: return: can only `return' from a function or sourced script

### ISSUE THREAD

**Issue by Arxcis** [technocake/goto#22]
```
jonasjso in ~/git/technocake/goto on master
$ goto list -v 
            code --> /usr/local/opt/goto
            goto --> https://github.com/technocake/goto
          github --> https://github.com/technocake/goto

jonasjso in ~/git/technocake/goto on master
$ goto code
/usr/local/bin/goto: line 25: return: can only `return' from a function or sourced script

```

**Comment by technocake** [comment]
check that you source start_goto somewhere,
This error is because it is missing

**Comment by technocake** [comment]
I checked now, goto will work fine after you start a new terminal session.
This happens because start_goto hasn't been sourced in your current shell yet.. 

Hmm a little mindboggling to fix this one. I guess the best fix for now is to tell the user to close the reopen the terminal. However, this is not what we want 👎

**Comment by Arxcis** [comment]
`goto goto` worked

**Comment by Arxcis** [comment]
Restarting terminal and it works
```
jonasjso in ~
$ goto code

jonasjso in /usr/local/opt/goto on master
$ 
```

**Comment by technocake** [comment]
This so close to beeing solved now that I close this issue.

#51 is making goto able to detect if it is run as a sourced command.
If not, it tells the user to add `source start_goto` to .bash_profile. 

You still would have to restart the terminal or do the sourcing yourself. 
That should be informed to the user. That is it.
