### ISSUE TITLE
Core focus of goto - About doing one thing well 

### ISSUE THREAD

**Issue by Arxcis** [technocake/goto#33]
In earlier discussions it has been mentioned that `goto` should follow a core Unix principle of "doing one thing well". For me, that one thing is opening bookmarked webpages from the terminal - `cd the internet`. 
I think that this should be the core focus. 

Opening local folders, files and programs, is something that is really well supported in most operating systems already. Imho `goto` should not try to do this before the core functionality is hammered down.

The early adopters of `goto` needs a clear message of what goto is, and I feel that focusing on desktop shortcuts in addition to web-chortcuts makes that message harder to clearify.

This post just describes a gut feeling I had, so just wanted to put it out there to get the discussion going.

**Comment by technocake** [comment]
I disagree that the core focus is to cd the web.
The core focus is to get to where the thing you need is, now, regardless of where it is.
Regardless of the protocol it is served through.

**Comment by Arxcis** [comment]
I don't disagree with this. As I said above, it was just a gut feeling.

I agree that it would be ideal for `goto` to be an abstraction serving multiple underlying protocols.
`goto <insert here>`, `goto anywhere`

Perhaps my concern/gut feeling is more about clarity under the surface. How will we deal with the complexity of handling different protocols? Should we just strap on support for anything that comes up as we go, or do we need to have a more systematic approach?

**Comment by Arxcis** [comment]
Web URL is one protocol, Github API is another. Should we have multiple protocols interchanging in a single goto statement?

**Comment by technocake** [comment]
We shall indeed redo the structure inside and be more systematic :). 

What I have in mind is to build up a plugin pattern. Where we let plugins register handlers for protocols

Also aditional constraints can be used in the plugin registration to make sure for instance the github plugin only "wakes up" on uris with protocol https and host=github.com

**Comment by technocake** [comment]
Also we could introduce a event model, and let plugins listen to events such as:

examples of events:
project added
magicword added
going to magiword
gone to magicword


this way we can for instance let say a "environment setup plugin" catch the event 

"going to magicword "code" ~/code/project1"

and then be made such that it will look for a startup script within that folder and run it when you use goto code

This introduces another topic about configuration. I think we should introduce a system and structure for configuring goto.  both general goto settings to adjust gotos behaviour on a global level and project specific configuration to take presedence over global goto settings.
 This way we can say that the normal handler of `goto magicword` should be to cd to the folder if it is a path, but in projectX we could configure goto to use a different behaviour and forninstance open the file explorer instead.

Plugins should also have a unified configuration language and convention. 


I have two candidates for config language. json or yaml. 

I prefer yaml to make it more "convenient" to edit config files for humans. 
On the other hand I see that json could be continued to be used here, since we store the magic in json. 

Regardless of language for configuration, I believe it would be very handy to also have a cli api to set config. Just like git config.

**Comment by Arxcis** [comment]
Closing issue as my initial answers have been answered. Good talk.
