### ISSUE TITLE
.bash_profile takes precendence of .profile - disabling all existing configuration in my terminal

### ISSUE THREAD

**Issue by Arxcis** [technocake/goto#6]
**Problem**
I have my terminal config stored in `~/.profile` on my mac. The `goto` installer creates a new file `~/.bash_profile` with the following line, if it does not exist.
```
source start_goto
```
`~/.bash_profile` takes precendence over `~/.profile` and therefore none of existing configuration is loaded.

*Before installation:*
<img width="532" alt="before" src="https://user-images.githubusercontent.com/3092618/45588351-cbd43780-b913-11e8-93d0-0007e05aa124.png">
*After goto install - all custom styling disabled*
<img width="757" alt="after" src="https://user-images.githubusercontent.com/3092618/45588350-cbd43780-b913-11e8-933b-48c62de340ca.png">

**Solution 1** 
Check if `.profile` or `.bash_profile` or `.bashrc` exists before appending. Could be a problem to know all different names to check for, across all different OS-es.

**Solution 2**
Source any other config from `~/.bash_profile` if it does not exist. (what i ended up doing). 
```
source ~/.profile
source start_goto
```
Advantage: you only have to check if `~/.bash_profile` exists. Disadvantage: You are hijacking the default config file, and the users may or may not be upset about this. You still have the same problem from solution 1.

**Solution 3**
Don't try to put anything in these files. Is it really necessary to do this at all ? Isn't it enough to have stuff in available in PATH?

**Comment by technocake** [comment]
The main reason for why you need start_goto sourced is to be able to run `goto cd <magicword>` and then have the terminal change working directory - as you would expect. The other reason is to setup auto completion for goto. (this must be done each time a terminal starts, as far as I know).

In order to change the working directory of the parent shell, i.e, your terminal, running a script simply will not work. It changes the working directory of the forked process, but not the shell you are in. Sourcing runs the script as it would if you typed the commands one by one - and so this is ultimately how goto circumvents this issue of being able to change working directory of the shell calling goto.


However, we discussed this - should the setup script touch your ~/.bash_profile without warning? 
The thought behind it doing that was to make setup a no-hazzle time and make goto work straight away. However it assumed every system would have a .bash_profile and that was the main entrypoint. It is a naïve assumption. 

I think the best solution could be to make goto prompt the user installing whether or not to append ~/.bash_profile .  If the user don't want to, because they know they have a different setup - they could be informed by what to do to make it work (i.e append it manually somewhere them self). 
I guess a reasoning for why this must be done also should be in place. 

Further discussion could go on to whether or not find ~/.bash_profile  -- I guess I'll have to read up on the bash startup files hierarchy.

**Comment by technocake** [comment]
Look at bin/goto  - https://github.com/technocake/goto/blob/master/bin/goto#L7-L11  - for how the cd-technique is implemented today.

**Comment by technocake** [comment]
Proposed fix is in pull request #12

**Comment by technocake** [comment]
Install script now asks  the user before it appends bash_profile
